### ISSUE TITLE
Load python in Matlab

### ISSUE THREAD

**Issue by zxdawn** [CohenBerkeleyLab/BEHR-PSM-Gridding#3]
This is the error after running BEHR_main.m:
```
   BEHR [NO2] stored for swath 1
   BEHR [NO2] stored for swath 2
Error using psm_wrapper (line 76)
Undefined variable "py" or class "py.PSM_Main.behr_datasets".

Error in BEHR_main_one_day (line 216)
OMI = psm_wrapper(Data, Data(1).Grid, 'only_cvm', ~use_psm, 'DEBUG_LEVEL',
DEBUG_LEVEL);

Error in BEHR_main (line 218)
parfor(j=1:length(datenums), n_workers)
```
I wrote a simple script named `haha.py` to **test loading python in Matlab**:
```
def a(text):
    print text
```
The result of running `py.haha.a('1')` was `1`. So, It seemed no bug.
But, if I run `py.PSM_Main.behr_datasets('cvm')` in `BEHR-PSM-Gridding` directory, I will get this error:
```
Undefined variable "py" or class "py.PSM_Main.behr_datasets".
```
Then, I **tested behr_datasets function in python**:
`$ from PSM_Main import behr_datasets`
```
/data/home/wang/anaconda2/envs/behr/lib/python2.7/site-packages/h5py-2.7.1-py2.7-linux-x86_64.egg/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
```
`$ behr_datasets('cvm')`
```
['TiledArea', 'TiledCornerLatitude', 'TiledCornerLongitude', 'FoV75Area', 'FoV75CornerLatitude', 'FoV75CornerLongitude', 'CloudRadianceFraction', 'CloudPressure', 'BEHRColumnAmountNO2Trop', 'ColumnAmountNO2Trop', 'ColumnAmountNO2TropStd', 'BEHRAMFTrop', 'VcdQualityFlags', 'XTrackQualityFlags', 'SolarZenithAngle', 'Time', 'Latitude', 'Longitude']
```
So, It worked fine by python2.7. To find out if the version of hdf5 affects this result, I compiled h5py=2.7.1 by hdf5=1.8.12 which is as same as Matlab's. But, I got the same error.

By the way,

1. I tried intel compiler first and used gnu finally because of other errors.
2. Loading python in Matlab only works after R2014b. I installed R2017a instead of R2014a.
3. I've tried deleting cgrate.c and recompiling the omi package when changing USE_CYTHON in setup.py from False to True.

**Comment by behr-github** [comment]
If you have Python 3 available, try using `pyversion` in Matlab to switch to using Python 3. When I updated from Matlab 2014b to 2017b, I had similar issues with Python 2. If you don't want to install h5py for python 3, you can switch to the `no-he5` branch for this repo, as the Python-Matlab interfaced code does not need the ability to load HDF5 files.

**Comment by zxdawn** [comment]
After testing, I found that Python 3 + h5py (hdf5=1.8.12) works fine for `develop` branch. If h5py is installed by pip or conda (which means hdf5 version isn't 1.8.12), it will get that issue.
