### ISSUE TITLE
Compare WRF-Chem VCD with the BEHR VCD

### ISSUE THREAD

**Issue by zxdawn** [CohenBerkeleyLab/BEHR-PSM-Gridding#4]
I'm trying to apply Averaging Kernels to WRF-Chem profile. Fortunately, Qindan has added WRF_AK_Column_NO2, WRF_AK_Column_NO2_Visonly, WRF_Column_NO2 to OMI. 

So, I changed branch from develop to flashcounts. But, I got this error when running BEHR_main.m:

```
Error using psm_wrapper (line 148)
Reference to non-existent field 'GitHead_Core_Main'.

Error in BEHR_main_one_day (line 230)
OMI = psm_wrapper(Data, Data(1).Grid, 'only_cvm', ~use_psm, 'DEBUG_LEVEL', DEBUG_LEVEL);

Error in BEHR_main (line 227)
parfor(j=1:length(datenums), n_workers)

```

**Comment by qdzhu** [comment]
Hi This is Qindan Zhu. The current version that BEHR releases to public is on master branch, the develop branch and also other branches are what Josh and I are working on. I strongly recommend you only use master branch as we can't guarantee the code to be right on other branches.
With regards to your specific question here, I add these three fields to produce NO2 VCD by multiplying NO2 mixing ratio from WRF-Chem by averaging kernel from BEHR. However, the changes I submit on the 'flashcounts' branch are only temporary and merely supports my work on the local computer. So I don't recommend you use any submits on this branch. 
I suggest you switching to master branch on each repository and if you have any questions using BEHR retrieval on master branch please let me know.
If you are interested in our current research, the paper written by Josh would be helpful.
https://www.atmos-meas-tech.net/10/4403/2017/
If you seek for further cooperation on BEHR development that your work is related to, please contact our group.
http://cohen.cchem.berkeley.edu/Home.aspx
Thanks!

**Comment by zxdawn** [comment]
@qdzhu Thank you, Qindan.
I have got two results of WRF-Chem with LNOx and without LNOx.
Differences between BEHRAMFTropVisOnly of these two results are 0, just like Josh said in his paper:

> Josh: the scattering weights are fairly uniform across all altitudes; thus, the impact of changes to the relative distribution of NO2 within the UT is minimized since a UV–visible satellite instrument is similarly sensitive to NO2 at any altitude under these conditions.

Furthermore, I want to check which one coincides with BEHRTropVisOnly NO2 VCD better. I will try to multiply NO2 mixing ratio from WRF-Chem by averaging kernel and add them to 'Data' in BEHR_main_one_day.m.
Thanks,
Xin

**Comment by behr-github** [comment]
Xin - this discussion is getting away from the typical discussion for a GitHub issue. I am going to close this and continue the discussion by email.
